// ============================================================
// White Soul Ibiza — Turso DB seed script
// Run: node seed-db.js
// ============================================================

const TURSO_URL = 'https://whitesoulibiza-therealmfkk.aws-eu-west-1.turso.io/v2/pipeline';
const TURSO_TOKEN = 'eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJhIjoicnciLCJpYXQiOjE3Nzk4NzYzODMsImlkIjoiMDE5ZTY4ZTYtMjYwMS03ZjNjLWI0NzktMTBjMzRmMGFlOWVlIiwicmlkIjoiOTdkNjc2NmQtYmNhOC00YWEwLWE1M2QtYTFmZjkzZWM1NjNhIn0.AYnPaVkNwWAttSV8Hhz6_bub4TipYJRSVd0GMokhTJwFG8_zRxuqyRjL0aBxoNOfjwc_McMjCKry7hbUG2VzCA';

const translations = {
  EN: {
    'nav.home': 'Home', 'nav.services': 'Services', 'nav.custom': 'Experiences',
    'nav.events': 'Events', 'nav.testimonials': 'Testimonials', 'nav.about': 'About', 'nav.contact': 'Contact',
    'cta.plan': 'Plan Your Experience', 'cta.discover': 'Discover Services', 'cta.start': 'Start Your Journey',
    'cta.create': 'Create Your Experience', 'cta.inquire': 'Begin Concierge Request',
    'cta.services': 'Explore All Services', 'cta.story': 'Our Story', 'cta.plan.event': 'Begin Planning',
    'home.hero.eyebrow': 'White Soul Ibiza · Est. 2018',
    'home.hero.sub': 'Bespoke villas, private yachts, chef-driven evenings, and tailor-made events — designed entirely around you. Privacy, exclusivity, and the unforgettable.',
    'home.intro.eyebrow': 'The White Soul Way',
    'home.intro.p1': "For over a decade, White Soul Ibiza has crafted private moments for those who arrive seeking more than a destination. We orchestrate seamless stays inside the island's most coveted villas, choreograph evenings beneath Mediterranean skies, and open doors that remain quietly closed to most.",
    'home.intro.p2': 'Our work is invisible and everywhere — anticipating the next gesture, the next pour, the next horizon. Every detail crafted for you.',
    'home.services.eyebrow': 'Our Services',
    'home.services.p': "A discreet team of specialists, sommeliers, captains, chefs, and event designers working as one.",
    'home.services.villa.name': 'Villa Concierge',
    'home.services.villa.desc': "Pre-arrival stocking, dedicated staff, transfers, and round-the-clock attention inside the island's finest residences.",
    'home.services.yacht.name': 'Yacht & Sea',
    'home.services.yacht.desc': 'Day charters and overnight voyages aboard sailing yachts, motor yachts, and bespoke vessels across the Balearic coast.',
    'home.services.chef.name': 'Private Chef',
    'home.services.chef.desc': "Michelin-trained chefs designing menus around your villa, your guests, your evening — from intimate suppers to grand tables.",
    'home.services.vip.name': 'VIP Reservations',
    'home.services.vip.desc': "Front-row tables at Ushuaïa, Pacha, Lío, Cipriani, Beso Beach — wherever Ibiza is happening tonight, you are there.",
    'home.services.wellness.name': 'Wellness',
    'home.services.wellness.desc': "In-villa massage, facials and holistic treatments — designed to restore, delivered in the privacy of your residence.",
    'home.services.events.name': 'Private Events',
    'home.services.events.desc': "Weddings, milestone celebrations, brand activations — every guest welcomed, every detail held quietly in our care.",
    'home.villas.eyebrow': 'Featured Villas',
    'home.villas.p': "A handpicked portfolio of the island's most remarkable homes — cliffside, hidden valleys, sea-facing terraces.",
    'home.testimonials.eyebrow': 'Words from our guests',
    'home.insta.eyebrow': '@whitesoul.ibiza',
    'home.cta.eyebrow': 'Begin',
    'home.cta.p': 'From the moment you write to us, your stay is in motion. One conversation. One curated proposal. One unforgettable arrival.',
    'services.hero.eyebrow': 'Our Services',
    'services.hero.sub': 'A single point of contact orchestrating every element of your Ibiza stay — from arrival to last lingering sunset.',
    'services.villa.eyebrow': 'Villa Concierge', 'services.villa.title': 'Your home, anticipated.',
    'services.villa.p': "From the moment your villa is booked, our team begins quietly preparing the rooms you'll move through. Linen turned, pantries stocked to your taste, transfers timed to the minute, and a discreet manager on call through every hour of your stay.",
    'services.villa.f1': 'Pre-arrival villa setup & personalised provisioning',
    'services.villa.f2': 'Dedicated 24/7 concierge & in-residence host',
    'services.villa.f3': 'Airport, helicopter and yacht transfers',
    'services.villa.f4': 'Housekeeping, laundry, butler & security',
    'services.chef.eyebrow': 'Private Chef in Villa', 'services.chef.title': 'A table made for you.',
    'services.chef.p': "Michelin-trained chefs arrive at your villa with a vision built from a single conversation. Mediterranean tasting menus, Japanese omakase, family-style suppers under the olive trees — every dish paired, every wine considered, every plate cleared without sound.",
    'services.chef.f1': 'Personalised menus shaped to dietary and cultural preferences',
    'services.chef.f2': 'Sommelier-curated wine pairings & rare-bottle sourcing',
    'services.chef.f3': 'Live cooking experiences & cocktail mixology',
    'services.chef.f4': 'Daily breakfast service & in-villa baker',
    'services.chef.f5': 'Private tastings, themed nights & chef tables',
    'services.yacht.eyebrow': 'Yacht & Boat Experiences', 'services.yacht.title': 'Beyond the shoreline.',
    'services.yacht.p': 'The Balearics unfold differently from the water. Sail to Formentera at first light, drop anchor at Cala Saladeta for lunch from the kitchen, return to your villa as the cliffs catch fire. Day cruises, overnight charters, or week-long voyages — captained by our trusted crew.',
    'services.yacht.f1': 'Sailing yachts, motor yachts, gulets & day-cruisers',
    'services.yacht.f2': 'Crewed charters with chef, captain & hostess',
    'services.yacht.f3': 'Formentera day trips & sunset itineraries',
    'services.yacht.f4': 'Water-sports: jet ski, paddle, foiling & scuba',
    'services.yacht.f5': 'Beach club arrivals & Cala Jondal reservations',
    'services.vip.eyebrow': 'VIP Services & Reservations', 'services.vip.title': 'Doors that open quietly.',
    'services.vip.p': "Ibiza's most coveted tables, terraces, and front-row tables — held in our name, given to you. We don't queue, we don't wait, and neither do you.",
    'services.vip.f1': 'VIP tables: Ushuaïa, Pacha, Lío, Hï, DC10',
    'services.vip.f2': 'Beach club privileges: Cipriani, Beso, Amante, Cotton',
    'services.vip.f3': 'Restaurant reservations across the island',
    'services.vip.f4': 'Deltaplano, supercar & vintage vehicle rentals',
    'services.vip.f5': 'Private DJ & artist bookings',
    'services.wellness.eyebrow': 'Wellness & Experiences', 'services.wellness.title': 'A quieter kind of luxury.',
    'services.wellness.p': "The island has long been a place of healing. We work with Ibiza's most respected therapists — designing rituals around your needs, in the privacy of your villa.",
    'services.wellness.f1': 'In-villa massage, facials & holistic treatments',
    'services.photo.eyebrow': 'Fotografia per Eventi', 'services.photo.title': 'Every moment, preserved.',
    'services.photo.p': 'From intimate villa celebrations to full-scale events, our trusted photographers capture the atmosphere, the details, and the people that make each occasion unique. Delivered as a curated gallery — timeless and elegant.',
    'services.photo.f1': 'Professional event & celebration photography',
    'services.photo.f2': 'Portraits, candid moments & venue details',
    'services.photo.f3': 'Same-day preview selections available',
    'services.photo.f4': 'Full gallery delivered within 2 weeks',
    'services.photo.f5': 'Drone & aerial photography on request',
    'services.cta.p': 'Tell us when you arrive, who is with you, and what would make this stay extraordinary. We take care of the rest.',
    'events.hero.eyebrow': 'Events & Celebrations',
    'events.hero.sub': 'Bachelor & bachelorette parties and exclusive VIP packages for the best nights in Ibiza — organised with care and discretion.',
    'events.intro.eyebrow': 'What we organise',
    'events.bachelorette.title': 'Addio al Celibato & Nubilato',
    'events.bachelorette.desc': 'The last great weekend before the wedding — curated, discreet and unforgettable. From a villa party to a night at the best clubs on the island.',
    'events.bachelorette.arrow': 'Discover →',
    'events.packages.title': 'Packages & Tables for Evenings',
    'events.packages.desc': 'VIP access, reserved tables and exclusive packages at the best venues and beach clubs in Ibiza — all arranged for you.',
    'events.packages.arrow': 'Discover →',
    'events.process.eyebrow': 'How we work', 'events.gallery.eyebrow': 'Past Events',
    'events.cta.p': 'Share the occasion, the date, the people. We will design the rest in full.',
    'footer.explore': 'Explore', 'footer.discover': 'Discover', 'footer.contact': 'Contact',
    'footer.tagline': '"Live Ibiza the White Soul way."',
  },
  IT: {
    'nav.home': 'Home', 'nav.services': 'Servizi', 'nav.custom': 'Esperienze',
    'nav.events': 'Eventi', 'nav.testimonials': 'Testimonianze', 'nav.about': 'Chi Siamo', 'nav.contact': 'Contatti',
    'cta.plan': 'Pianifica la Tua Esperienza', 'cta.discover': 'Scopri i Servizi', 'cta.start': "Inizia il Tuo Viaggio",
    'cta.create': 'Crea la Tua Esperienza', 'cta.inquire': 'Inizia Richiesta Concierge',
    'cta.services': 'Esplora Tutti i Servizi', 'cta.story': 'La Nostra Storia', 'cta.plan.event': 'Inizia a Pianificare',
    'home.hero.eyebrow': 'White Soul Ibiza · Est. 2018',
    'home.hero.sub': "Ville esclusive, yacht privati, serate con chef d'autore ed eventi su misura — progettati interamente attorno a te. Privacy, esclusività e l'indimenticabile.",
    'home.intro.eyebrow': 'Il Metodo White Soul',
    'home.intro.p1': "Da oltre un decennio, White Soul Ibiza crea momenti privati per chi arriva cercando qualcosa di più di una destinazione. Orchestriamo soggiorni perfetti nelle ville più ambite dell'isola, coreografiamo serate sotto i cieli del Mediterraneo e apriamo porte che restano discretamente chiuse a molti.",
    'home.intro.p2': 'Il nostro lavoro è invisibile e ovunque — anticipando il prossimo gesto, il prossimo brindisi, il prossimo orizzonte. Ogni dettaglio curato per te.',
    'home.services.eyebrow': 'I Nostri Servizi',
    'home.services.p': 'Un team discreto di specialisti, sommelier, capitani, chef e designer di eventi che lavorano come uno.',
    'home.services.villa.name': 'Concierge Villa',
    'home.services.villa.desc': "Approvvigionamento pre-arrivo, personale dedicato, trasferimenti e attenzione 24 ore su 24 nelle residenze più belle dell'isola.",
    'home.services.yacht.name': 'Yacht & Mare',
    'home.services.yacht.desc': 'Gite in giornata e viaggi notturni a bordo di yacht a vela, motoryacht e imbarcazioni su misura lungo la costa Balearica.',
    'home.services.chef.name': 'Chef Privato',
    'home.services.chef.desc': "Chef di formazione Michelin che progettano menu attorno alla tua villa, ai tuoi ospiti, alla tua serata.",
    'home.services.vip.name': 'Prenotazioni VIP',
    'home.services.vip.desc': "Tavoli in prima fila a Ushuaïa, Pacha, Lío, Cipriani, Beso Beach — dove succede Ibiza stanotte, voi siete lì.",
    'home.services.wellness.name': 'Wellness',
    'home.services.wellness.desc': "Massaggi in villa, trattamenti viso e terapie olistiche — progettati per rigenerare, offerti nella privacy della tua residenza.",
    'home.services.events.name': 'Eventi Privati',
    'home.services.events.desc': 'Matrimoni, celebrazioni importanti, attivazioni di brand — ogni ospite accolto, ogni dettaglio curato con discrezione.',
    'home.villas.eyebrow': 'Ville in Evidenza',
    'home.villas.p': "Un portfolio selezionato delle case più straordinarie dell'isola — a picco sul mare, in valli nascoste, con terrazze sul mare.",
    'home.testimonials.eyebrow': 'Le parole dei nostri ospiti',
    'home.insta.eyebrow': '@whitesoul.ibiza',
    'home.cta.eyebrow': 'Inizia',
    'home.cta.p': 'Dal momento in cui ci scrivi, il tuo soggiorno è già in movimento. Una conversazione. Una proposta curata. Un arrivo indimenticabile.',
    'services.hero.eyebrow': 'I Nostri Servizi',
    'services.hero.sub': "Un unico punto di contatto per orchestrare ogni elemento del tuo soggiorno a Ibiza — dall'arrivo all'ultimo tramonto.",
    'services.villa.eyebrow': 'Concierge Villa', 'services.villa.title': 'La tua casa, anticipata.',
    'services.villa.p': "Dal momento in cui la villa è prenotata, il nostro team inizia silenziosamente a preparare gli spazi che attraverserai. Biancheria pronta, dispensa rifornita secondo i tuoi gusti, trasferimenti puntuali al minuto e un manager discreto reperibile ogni ora del tuo soggiorno.",
    'services.villa.f1': 'Allestimento pre-arrivo della villa & approvvigionamento personalizzato',
    'services.villa.f2': 'Concierge dedicato 24/7 & host in residenza',
    'services.villa.f3': 'Trasferimenti aeroporto, elicottero e yacht',
    'services.villa.f4': 'Pulizie, lavanderia, butler & sicurezza',
    'services.chef.eyebrow': 'Chef Privato in Villa', 'services.chef.title': 'Una tavola pensata per te.',
    'services.chef.p': "Chef di formazione Michelin arrivano alla tua villa con una visione costruita su una singola conversazione. Menu degustazione mediterranei, omakase giapponese, cene in stile familiare sotto gli ulivi.",
    'services.chef.f1': 'Menu personalizzati secondo preferenze alimentari e culturali',
    'services.chef.f2': 'Abbinamenti vini curati da sommelier & reperimento bottiglie rare',
    'services.chef.f3': 'Esperienze di cucina dal vivo & mixology di cocktail',
    'services.chef.f4': 'Servizio colazione quotidiano & fornaio in villa',
    'services.chef.f5': 'Degustazioni private, serate a tema & chef table',
    'services.yacht.eyebrow': 'Esperienze Yacht & Barca', 'services.yacht.title': 'Oltre la riva.',
    'services.yacht.p': "Le Baleari si svelano diversamente dall'acqua. Veleggia verso Formentera alle prime luci dell'alba, getta l'ancora a Cala Saladeta per il pranzo, torna alla tua villa mentre le scogliere si accendono.",
    'services.yacht.f1': 'Yacht a vela, motoryacht, gulet & day-cruiser',
    'services.yacht.f2': 'Charter con equipaggio: chef, capitano & hostess',
    'services.yacht.f3': 'Gite a Formentera & itinerari al tramonto',
    'services.yacht.f4': 'Sport acquatici: jet ski, paddle, foiling & scuba',
    'services.yacht.f5': 'Arrivi ai beach club & prenotazioni Cala Jondal',
    'services.vip.eyebrow': 'Servizi VIP & Prenotazioni', 'services.vip.title': 'Porte che si aprono in silenzio.',
    'services.vip.p': "I tavoli, le terrazze e i posti in prima fila più ambiti di Ibiza — riservati a nostro nome, ceduti a te. Non aspettiamo in fila, e nemmeno voi.",
    'services.vip.f1': 'Tavoli VIP: Ushuaïa, Pacha, Lío, Hï, DC10',
    'services.vip.f2': 'Privilegi beach club: Cipriani, Beso, Amante, Cotton',
    "services.vip.f3": "Prenotazioni ristoranti su tutta l'isola",
    'services.vip.f4': 'Deltaplano, supercar & noleggio veicoli d\'epoca',
    'services.vip.f5': 'Prenotazioni DJ privato & artisti',
    'services.wellness.eyebrow': 'Wellness & Esperienze', 'services.wellness.title': 'Un lusso più silenzioso.',
    'services.wellness.p': "L'isola è da sempre un luogo di guarigione. Collaboriamo con i terapisti più rispettati di Ibiza — progettando rituali attorno alle tue esigenze, nella privacy della tua villa.",
    'services.wellness.f1': 'Massaggi in villa, trattamenti viso & terapie olistiche',
    'services.photo.eyebrow': 'Fotografia per Eventi', 'services.photo.title': 'Ogni momento, preservato.',
    'services.photo.p': "Da celebrazioni intime in villa a eventi su larga scala, i nostri fotografi di fiducia catturano l'atmosfera, i dettagli e le persone che rendono ogni occasione unica. Consegnata come una galleria curata — senza tempo ed elegante.",
    'services.photo.f1': 'Fotografia professionale per eventi e celebrazioni',
    'services.photo.f2': 'Ritratti, momenti spontanei & dettagli della location',
    'services.photo.f3': 'Selezione anteprima in giornata disponibile',
    'services.photo.f4': 'Galleria completa consegnata entro 2 settimane',
    'services.photo.f5': 'Fotografia con drone & riprese aeree su richiesta',
    'services.cta.p': 'Dicci quando arrivi, chi è con te e cosa renderebbe questo soggiorno straordinario. Pensiamo noi al resto.',
    'events.hero.eyebrow': 'Eventi & Celebrazioni',
    'events.hero.sub': 'Addio al celibato, nubilato e pacchetti VIP per le migliori serate di Ibiza — organizzati con cura e discrezione.',
    'events.intro.eyebrow': 'Cosa organizziamo',
    'events.bachelorette.title': 'Addio al Celibato & Nubilato',
    'events.bachelorette.desc': "L'ultimo grande weekend prima del matrimonio — curato, discreto e indimenticabile. Dal party in villa alla notte nei migliori club dell'isola.",
    'events.bachelorette.arrow': 'Scopri →',
    'events.packages.title': 'Pacchetti & Tavoli per le Serate',
    'events.packages.desc': 'Accesso VIP, tavoli riservati e pacchetti esclusivi nei migliori locali e beach club di Ibiza — tutto organizzato per voi.',
    'events.packages.arrow': 'Scopri →',
    'events.process.eyebrow': 'Come lavoriamo', 'events.gallery.eyebrow': 'Serate passate',
    'events.cta.p': 'Dicci l\'occasione, la data, le persone. Progetteremo il resto nel dettaglio.',
    'footer.explore': 'Esplora', 'footer.discover': 'Scopri', 'footer.contact': 'Contatti',
    'footer.tagline': '"Vivi Ibiza alla maniera White Soul."',
  },
  ES: {
    'nav.home': 'Inicio', 'nav.services': 'Servicios', 'nav.custom': 'Experiencias',
    'nav.events': 'Eventos', 'nav.testimonials': 'Testimonios', 'nav.about': 'Nosotros', 'nav.contact': 'Contacto',
    'cta.plan': 'Planea Tu Experiencia', 'cta.discover': 'Descubre Servicios', 'cta.start': 'Comienza Tu Viaje',
    'cta.create': 'Crea Tu Experiencia', 'cta.inquire': 'Solicitud de Conserje',
    'cta.services': 'Ver Todos los Servicios', 'cta.story': 'Nuestra Historia', 'cta.plan.event': 'Empieza a Planificar',
    'home.hero.eyebrow': 'White Soul Ibiza · Est. 2018',
    'home.hero.sub': 'Villas exclusivas, yates privados, veladas con chef y eventos a medida — diseñados completamente para ti. Privacidad, exclusividad e inolvidable.',
    'home.intro.eyebrow': 'El Método White Soul',
    'home.intro.p1': 'Durante más de una década, White Soul Ibiza ha creado momentos privados para quienes llegan buscando algo más que un destino. Orquestamos estancias perfectas en las villas más codiciadas de la isla, coreografiamos veladas bajo los cielos mediterráneos y abrimos puertas que permanecen discretamente cerradas para la mayoría.',
    'home.intro.p2': 'Nuestro trabajo es invisible y está en todas partes — anticipando el próximo gesto, la próxima copa, el próximo horizonte. Cada detalle diseñado para ti.',
    'home.services.eyebrow': 'Nuestros Servicios',
    'home.services.p': 'Un discreto equipo de especialistas, sommeliers, capitanes, chefs y diseñadores de eventos trabajando como uno.',
    'home.services.villa.name': 'Conserje de Villa',
    'home.services.villa.desc': 'Aprovisionamiento previo a la llegada, personal dedicado, traslados y atención permanente en las mejores residencias de la isla.',
    'home.services.yacht.name': 'Yate & Mar',
    'home.services.yacht.desc': 'Excursiones de un día y travesías nocturnas a bordo de veleros, yates a motor y embarcaciones a medida por la costa balear.',
    'home.services.chef.name': 'Chef Privado',
    'home.services.chef.desc': 'Chefs de formación Michelin que diseñan menús alrededor de tu villa, tus invitados, tu velada.',
    'home.services.vip.name': 'Reservas VIP',
    'home.services.vip.desc': 'Mesas de primera fila en Ushuaïa, Pacha, Lío, Cipriani, Beso Beach — donde ocurre Ibiza esta noche, tú estás allí.',
    'home.services.wellness.name': 'Bienestar',
    'home.services.wellness.desc': 'Masajes en villa, faciales y tratamientos holísticos — diseñados para restaurar, entregados en la privacidad de tu residencia.',
    'home.services.events.name': 'Eventos Privados',
    'home.services.events.desc': 'Bodas, celebraciones especiales, activaciones de marca — cada detalle cuidado con discreción.',
    'home.villas.eyebrow': 'Villas Destacadas',
    'home.villas.p': 'Un portfolio seleccionado de las casas más extraordinarias de la isla — en acantilados, valles escondidos, terrazas frente al mar.',
    'home.testimonials.eyebrow': 'Las palabras de nuestros huéspedes',
    'home.insta.eyebrow': '@whitesoul.ibiza',
    'home.cta.eyebrow': 'Empieza',
    'home.cta.p': 'Desde el momento en que nos escribes, tu estancia está en marcha. Una conversación. Una propuesta curada. Una llegada inolvidable.',
    'services.hero.eyebrow': 'Nuestros Servicios',
    'services.hero.sub': 'Un único punto de contacto que orquesta cada elemento de tu estancia en Ibiza — desde la llegada hasta el último atardecer.',
    'services.villa.eyebrow': 'Conserje de Villa', 'services.villa.title': 'Tu hogar, anticipado.',
    'services.villa.p': 'Desde el momento en que se reserva la villa, nuestro equipo empieza a preparar silenciosamente los espacios que recorrerás. Ropa de cama lista, despensa surtida a tu gusto, traslados cronometrados al minuto.',
    'services.villa.f1': 'Configuración pre-llegada de la villa & aprovisionamiento personalizado',
    'services.villa.f2': 'Conserje dedicado 24/7 & anfitrión en residencia',
    'services.villa.f3': 'Traslados aeropuerto, helicóptero y yate',
    'services.villa.f4': 'Limpieza, lavandería, mayordomo & seguridad',
    'services.chef.eyebrow': 'Chef Privado en Villa', 'services.chef.title': 'Una mesa hecha para ti.',
    'services.chef.p': 'Chefs de formación Michelin llegan a tu villa con una visión construida a partir de una sola conversación.',
    'services.chef.f1': 'Menús personalizados según preferencias dietéticas y culturales',
    'services.chef.f2': 'Maridajes de vinos curados por sommelier & botellas exclusivas',
    'services.chef.f3': 'Experiencias de cocina en vivo & mixología de cócteles',
    'services.chef.f4': 'Servicio de desayuno diario & panadero en villa',
    "services.chef.f5": "Catas privadas, noches temáticas & chef's table",
    'services.yacht.eyebrow': 'Experiencias Yate & Barco', 'services.yacht.title': 'Más allá de la orilla.',
    'services.yacht.p': 'Las Baleares se despliegan de forma diferente desde el agua. Navega hacia Formentera al amanecer, fondea en Cala Saladeta para el almuerzo.',
    'services.yacht.f1': 'Veleros, yates a motor, gullets & day-cruisers',
    'services.yacht.f2': 'Chárter con tripulación: chef, capitán & azafata',
    'services.yacht.f3': 'Excursiones a Formentera & itinerarios al atardecer',
    'services.yacht.f4': 'Deportes acuáticos: jet ski, paddle, foiling & buceo',
    'services.yacht.f5': 'Llegadas a beach clubs & reservas Cala Jondal',
    'services.vip.eyebrow': 'Servicios VIP & Reservas', 'services.vip.title': 'Puertas que se abren en silencio.',
    'services.vip.p': 'Las mesas, terrazas y primeras filas más codiciadas de Ibiza — reservadas a nuestro nombre, entregadas a ti.',
    'services.vip.f1': 'Mesas VIP: Ushuaïa, Pacha, Lío, Hï, DC10',
    'services.vip.f2': 'Privilegios beach club: Cipriani, Beso, Amante, Cotton',
    'services.vip.f3': 'Reservas en restaurantes de toda la isla',
    'services.vip.f4': 'Ala delta, supercoches & alquiler de vehículos vintage',
    'services.vip.f5': 'Contratación de DJ privado & artistas',
    'services.wellness.eyebrow': 'Bienestar & Experiencias', 'services.wellness.title': 'Un lujo más silencioso.',
    'services.wellness.p': 'La isla ha sido durante mucho tiempo un lugar de sanación. Trabajamos con los terapeutas más respetados de Ibiza, diseñando rituales según tus necesidades.',
    'services.wellness.f1': 'Masajes en villa, faciales & tratamientos holísticos',
    'services.photo.eyebrow': 'Fotografía para Eventos', 'services.photo.title': 'Cada momento, preservado.',
    'services.photo.p': 'Desde celebraciones íntimas en villa hasta eventos a gran escala, nuestros fotógrafos de confianza capturan la atmósfera, los detalles y las personas que hacen única cada ocasión.',
    'services.photo.f1': 'Fotografía profesional para eventos y celebraciones',
    'services.photo.f2': 'Retratos, momentos espontáneos & detalles del espacio',
    'services.photo.f3': 'Selección de vista previa el mismo día disponible',
    'services.photo.f4': 'Galería completa entregada en 2 semanas',
    'services.photo.f5': 'Fotografía con dron & aérea bajo petición',
    'services.cta.p': 'Dinos cuándo llegas, quién te acompaña y qué haría este viaje extraordinario. Nosotros nos encargamos del resto.',
    'events.hero.eyebrow': 'Eventos & Celebraciones',
    'events.hero.sub': 'Despedidas de soltero/a y paquetes VIP exclusivos para las mejores noches en Ibiza — organizados con cuidado y discreción.',
    'events.intro.eyebrow': 'Qué organizamos',
    'events.bachelorette.title': 'Despedida de Soltero & Soltera',
    'events.bachelorette.desc': 'El último gran fin de semana antes de la boda — cuidado, discreto e inolvidable. Desde una fiesta en villa hasta una noche en los mejores clubs de la isla.',
    'events.bachelorette.arrow': 'Descubrir →',
    'events.packages.title': 'Paquetes & Mesas para las Noches',
    'events.packages.desc': 'Acceso VIP, mesas reservadas y paquetes exclusivos en los mejores locales y beach clubs de Ibiza — todo organizado para vosotros.',
    'events.packages.arrow': 'Descubrir →',
    'events.process.eyebrow': 'Cómo trabajamos', 'events.gallery.eyebrow': 'Eventos pasados',
    'events.cta.p': 'Cuéntanos la ocasión, la fecha, las personas. Diseñaremos el resto en su totalidad.',
    'footer.explore': 'Explorar', 'footer.discover': 'Descubrir', 'footer.contact': 'Contacto',
    'footer.tagline': '"Vive Ibiza a la manera White Soul."',
  },
  FR: {
    'nav.home': 'Accueil', 'nav.services': 'Services', 'nav.custom': 'Expériences',
    'nav.events': 'Événements', 'nav.testimonials': 'Témoignages', 'nav.about': 'À Propos', 'nav.contact': 'Contact',
    'cta.plan': 'Planifiez Votre Expérience', 'cta.discover': 'Découvrir les Services', 'cta.start': 'Commencez Votre Voyage',
    'cta.create': 'Créez Votre Expérience', 'cta.inquire': 'Demande de Conciergerie',
    'cta.services': 'Voir Tous les Services', 'cta.story': 'Notre Histoire', 'cta.plan.event': 'Commencer à Planifier',
    'home.hero.eyebrow': 'White Soul Ibiza · Est. 2018',
    'home.hero.sub': "Villas privées, yachts exclusifs, dîners avec chef étoilé et événements sur mesure — conçus entièrement pour vous. Intimité, exclusivité et inoubliable.",
    'home.intro.eyebrow': 'La Méthode White Soul',
    'home.intro.p1': "Depuis plus d'une décennie, White Soul Ibiza crée des moments privés pour ceux qui arrivent en quête de plus qu'une destination. Nous orchestrons des séjours parfaits dans les villas les plus convoitées de l'île, chorégraphions des soirées sous les cieux méditerranéens et ouvrons des portes discrètement fermées pour la plupart.",
    'home.intro.p2': 'Notre travail est invisible et partout — anticipant le prochain geste, la prochaine coupe, le prochain horizon. Chaque détail conçu pour vous.',
    'home.services.eyebrow': 'Nos Services',
    'home.services.p': "Un équipe discrète de spécialistes, sommeliers, capitaines, chefs et designers d'événements travaillant en harmonie.",
    'home.services.villa.name': 'Conciergerie Villa',
    'home.services.villa.desc': "Approvisionnement avant l'arrivée, personnel dédié, transferts et attention permanente dans les plus belles résidences de l'île.",
    'home.services.yacht.name': 'Yacht & Mer',
    'home.services.yacht.desc': "Excursions à la journée et traversées nocturnes à bord de voiliers, yachts à moteur et embarcations sur mesure le long de la côte baléare.",
    'home.services.chef.name': 'Chef Privé',
    'home.services.chef.desc': 'Des chefs de formation Michelin créent des menus autour de votre villa, vos convives, votre soirée.',
    'home.services.vip.name': 'Réservations VIP',
    'home.services.vip.desc': "Tables au premier rang à Ushuaïa, Pacha, Lío, Cipriani, Beso Beach — où Ibiza se passe ce soir, vous y êtes.",
    'home.services.wellness.name': 'Bien-être',
    'home.services.wellness.desc': "Massages en villa, soins du visage et thérapies holistiques — conçus pour restaurer, offerts dans l'intimité de votre résidence.",
    'home.services.events.name': 'Événements Privés',
    'home.services.events.desc': 'Mariages, célébrations importantes, activations de marque — chaque détail soigné avec discrétion.',
    'home.villas.eyebrow': 'Villas en Vedette',
    'home.villas.p': "Un portfolio sélectionné des maisons les plus remarquables de l'île — falaises, vallées cachées, terrasses face à la mer.",
    'home.testimonials.eyebrow': 'Les mots de nos hôtes',
    'home.insta.eyebrow': '@whitesoul.ibiza',
    'home.cta.eyebrow': 'Commencer',
    'home.cta.p': "Dès que vous nous écrivez, votre séjour est en mouvement. Une conversation. Une proposition curatée. Une arrivée inoubliable.",
    'services.hero.eyebrow': 'Nos Services',
    'services.hero.sub': "Un interlocuteur unique orchestrant chaque élément de votre séjour à Ibiza — de l'arrivée au dernier coucher de soleil.",
    'services.villa.eyebrow': 'Conciergerie Villa', 'services.villa.title': 'Votre maison, anticipée.',
    'services.villa.p': "Dès la réservation de la villa, notre équipe commence discrètement à préparer les espaces que vous parcourrez.",
    'services.villa.f1': "Installation pré-arrivée de la villa & approvisionnement personnalisé",
    'services.villa.f2': 'Concierge dédié 24/7 & hôte en résidence',
    'services.villa.f3': 'Transferts aéroport, hélicoptère et yacht',
    'services.villa.f4': 'Ménage, blanchisserie, majordome & sécurité',
    'services.chef.eyebrow': 'Chef Privé en Villa', 'services.chef.title': 'Une table faite pour vous.',
    'services.chef.p': "Des chefs de formation Michelin arrivent dans votre villa avec une vision construite à partir d'une seule conversation.",
    'services.chef.f1': 'Menus personnalisés selon les préférences alimentaires et culturelles',
    'services.chef.f2': 'Accords mets-vins curatés par sommelier & vins rares',
    'services.chef.f3': 'Expériences culinaires en direct & mixologie',
    'services.chef.f4': 'Service petit-déjeuner quotidien & boulanger en villa',
    "services.chef.f5": "Dégustations privées, soirées à thème & chef's table",
    'services.yacht.eyebrow': 'Expériences Yacht & Bateau', 'services.yacht.title': 'Au-delà du rivage.',
    'services.yacht.p': "Les Baléares se révèlent différemment depuis l'eau. Naviguez vers Formentera à l'aube, jetez l'ancre à Cala Saladeta pour le déjeuner.",
    'services.yacht.f1': 'Voiliers, yachts à moteur, gulets & day-cruisers',
    'services.yacht.f2': 'Charters avec équipage : chef, capitaine & hôtesse',
    'services.yacht.f3': 'Excursions à Formentera & itinéraires au coucher du soleil',
    'services.yacht.f4': 'Sports nautiques : jet ski, paddle, foiling & plongée',
    'services.yacht.f5': 'Arrivées en beach clubs & réservations Cala Jondal',
    'services.vip.eyebrow': 'Services VIP & Réservations', 'services.vip.title': "Des portes qui s'ouvrent discrètement.",
    'services.vip.p': "Les tables, terrasses et premières loges les plus convoitées d'Ibiza — réservées en notre nom, offertes à vous.",
    'services.vip.f1': 'Tables VIP : Ushuaïa, Pacha, Lío, Hï, DC10',
    'services.vip.f2': 'Privilèges beach clubs : Cipriani, Beso, Amante, Cotton',
    "services.vip.f3": "Réservations restaurants dans toute l'île",
    'services.vip.f4': 'Deltaplane, supercars & location de véhicules vintage',
    'services.vip.f5': 'Réservation DJ privé & artistes',
    'services.wellness.eyebrow': 'Bien-être & Expériences', 'services.wellness.title': 'Un luxe plus silencieux.',
    'services.wellness.p': "L'île est depuis longtemps un lieu de guérison. Nous travaillons avec les thérapeutes les plus respectés d'Ibiza, concevant des rituels selon vos besoins.",
    'services.wellness.f1': 'Massages en villa, soins du visage & thérapies holistiques',
    'services.photo.eyebrow': 'Photographie pour Événements', 'services.photo.title': 'Chaque moment, préservé.',
    'services.photo.p': "Des célébrations intimes en villa aux événements à grande échelle, nos photographes de confiance capturent l'atmosphère, les détails et les personnes qui rendent chaque occasion unique.",
    'services.photo.f1': "Photographie professionnelle d'événements et célébrations",
    'services.photo.f2': 'Portraits, moments spontanés & détails du lieu',
    'services.photo.f3': 'Sélection aperçu le jour même disponible',
    'services.photo.f4': 'Galerie complète livrée sous 2 semaines',
    'services.photo.f5': 'Photographie par drone & aérienne sur demande',
    'services.cta.p': 'Dites-nous quand vous arrivez, qui vous accompagne et ce qui rendrait ce séjour extraordinaire. Nous nous occupons du reste.',
    'events.hero.eyebrow': 'Événements & Célébrations',
    'events.hero.sub': "Enterrements de vie de garçon/jeune fille et forfaits VIP exclusifs pour les meilleures soirées à Ibiza — organisés avec soin et discrétion.",
    'events.intro.eyebrow': 'Ce que nous organisons',
    'events.bachelorette.title': 'EVJF & EVG',
    'events.bachelorette.desc': "Le dernier grand week-end avant le mariage — organisé, discret et inoubliable. De la fête en villa à la nuit dans les meilleurs clubs de l'île.",
    'events.bachelorette.arrow': 'Découvrir →',
    'events.packages.title': 'Forfaits & Tables pour les Soirées',
    'events.packages.desc': "Accès VIP, tables réservées et forfaits exclusifs dans les meilleurs établissements et beach clubs d'Ibiza — tout organisé pour vous.",
    'events.packages.arrow': 'Découvrir →',
    'events.process.eyebrow': 'Comment nous travaillons', 'events.gallery.eyebrow': 'Soirées passées',
    'events.cta.p': 'Partagez l\'occasion, la date, les personnes. Nous concevrons le reste dans les moindres détails.',
    'footer.explore': 'Explorer', 'footer.discover': 'Découvrir', 'footer.contact': 'Contact',
    'footer.tagline': '"Vivez Ibiza à la manière White Soul."',
  }
};

async function turso(sql, args = []) {
  const res = await fetch(TURSO_URL, {
    method: 'POST',
    headers: { 'Authorization': `Bearer ${TURSO_TOKEN}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({
      requests: [
        { type: 'execute', stmt: { sql, args: args.map(v => ({ type: 'text', value: String(v) })) } },
        { type: 'close' }
      ]
    })
  });
  return res.json();
}

async function seed() {
  console.log('Seeding translations into Turso...');

  // Build all rows
  const rows = [];
  for (const [lang, dict] of Object.entries(translations)) {
    for (const [key, value] of Object.entries(dict)) {
      rows.push([lang, key, value]);
    }
  }

  // Insert in batches of 30
  const BATCH = 30;
  let inserted = 0;
  for (let i = 0; i < rows.length; i += BATCH) {
    const batch = rows.slice(i, i + BATCH);
    const requests = batch.map(([lang, key, value]) => ({
      type: 'execute',
      stmt: {
        sql: 'INSERT OR REPLACE INTO translations (lang, key, value) VALUES (?, ?, ?)',
        args: [
          { type: 'text', value: lang },
          { type: 'text', value: key },
          { type: 'text', value: value }
        ]
      }
    }));
    requests.push({ type: 'close' });

    const res = await fetch(TURSO_URL, {
      method: 'POST',
      headers: { 'Authorization': `Bearer ${TURSO_TOKEN}`, 'Content-Type': 'application/json' },
      body: JSON.stringify({ requests })
    });
    const data = await res.json();
    const errors = data.results.filter(r => r.type === 'error');
    if (errors.length) {
      console.error('Errors in batch:', JSON.stringify(errors));
    } else {
      inserted += batch.length;
      process.stdout.write(`\rInserted ${inserted}/${rows.length} rows...`);
    }
  }

  console.log(`\nDone. ${inserted} translation rows seeded.`);

  // Verify count
  const count = await turso('SELECT COUNT(*) as n FROM translations');
  const n = count.results[0].response.result.rows[0][0].value;
  console.log(`Total rows in DB: ${n}`);
}

seed().catch(console.error);
